### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by ChristopherHogan** [waltligon/orangefs#76]
From the [docs](http://docs.orangefs.com/home/index.htm) page, there are a couple dead links:

* [PVFS2](http://www.omnibond.com/orangefs/docs/pvfs2/index.htm)
* [Link to Source Code Documentation](http://www.orangefs.org/documentation/releases/current/doc/doxygen/html/)

**Comment by nathanweeks** [comment]
Also, there are two links to the pvfs2-users mailing list in the following sections 4.2 and 4.3 of the [FAQ](http://www.orangefs.org/faq), neither of which work:

* http://www.pvfs.org/pvfs2/lists.html
* http://www.beowulf-underground.org/mailman/listinfo/pvfs2-users

**Comment by dschwoerer** [comment]
Also, it would be great if the download links on https://www.orangefs.org/ would use https://

Browser will start warning, and later blocking plain http:// downloads without tls

**Comment by boydwilson** [comment]
We have migrated the docs to Hugo format so part A should be fixed, Dead links in Part B, has been fixed, Part C, right now where the docs are hosted that is a pain, but it is something we are working on (https everywhere) - going to close knowing we are still working on part C.
